baseurl = "https://magicloadr.com"
languageCode = "en-us"
title = "MagicLoadr"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 8
disqusShortname = "magicloadr"
copyright = "(c) 2018 Keith Brink"
googleAnalytics = "UA-112917572-1"
publishDir = "docs"

[params]
	subtitle = "Automatically Insert Cards into Toploaders"
	[params.author]
		name = "Keith Brink"
		avatar = "/images/avatar.jpg"
		bio = ""
		github = "keithbrink"
	[params.image]
	  feature = "/images/samuel-zeller-118178.jpg"
	  credit = "Samuel Zeller"
	  creditlink = "https://unsplash.com/photos/2BHDrWzyCto"
